### ISSUE TITLE
[Question] - How Can I use the list in my yaml?

### ISSUE THREAD

**Issue by julioNico** [AlexxNB/chalogen#3]
Hello, sorry about my question, I am learning github actions... I dont understand how can I use the **list**:

list – Conventional types list to include in changelog. Default: feat,fix,perf,docs,other

I need **HELP** to add the following elements in addition to Default:
BREAKING CHANGE, build, chore:, ci, style, refactor and test.

I tried that but it didn't work:

```
name: Generate Changelog

on:
  push:
    branches: [ main, master]

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update Changelog
        uses: AlexxNB/chalogen@master
        with:
          title: My project changelog
          list: BREAKING CHANGE, feat, fix, build, chore, ci, docs, style, refactor, perf, test, others #Conventional Commits

      - name: Commit Changelog to repository
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: 'docs(Changelog): Update Changelog'
          file_pattern: CHANGELOG.md
```

THANKS
